require: rubocop-rspec

Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/*'

Lint/MissingSuper:
  Exclude:
    - '**/*_plugin.rb'

AllCops:
  NewCops: enable
  Exclude:
    - 'spec/spec_helper.rb'
    - 'lib/old/*'